export const notificationsData = [
    {
      href: "#",
      imgSrc: "/assets/images/avatars/avatar-3.jpg",
      imgAlt: "Alexa Gray",
      message: "Alexa Gray started following you. Welcome him to your profile. 👋",
      time: "4 hours ago",
      bgClass: "bg-teal-500/5",
      button: null,
    },
    {
      href: "#",
      imgSrc: "/assets/images/avatars/avatar-7.jpg",
      imgAlt: "Jesse Steeve",
      message: "Jesse Steeve mentioned you in a story. Check it out and reply. 📣",
      time: "8 hours ago",
      bgClass: "",
      button: null,
    },
    {
      href: "#",
      imgSrc: "/assets/images/avatars/avatar-6.jpg",
      imgAlt: "Alexa Stella",
      message: "Alexa Stella commented on your photo “Wow, stunning shot!” 💬",
      time: "8 hours ago",
      bgClass: "",
      button: null,
    },
    {
      href: "#",
      imgSrc: "/assets/images/avatars/avatar-2.jpg",
      imgAlt: "John Michael",
      message: "John Michael who you might know, is on socialite.",
      time: "2 hours ago",
      bgClass: "",
      button: <button type="button" className="button text-white bg-primary">Follow</button>,
    },
    {
      href: "#",
      imgSrc: "/assets/images/avatars/avatar-2.jpg",
      imgAlt: "Lewis Lewis",
      message: "Lewis Lewis mentioned you in a story. Check it out and reply. 📣",
      time: "8 hours ago",
      bgClass: "",
      button: null,
    },
    {
      href: "#",
      imgSrc: "/assets/images/avatars/avatar-7.jpg",
      imgAlt: "Martin Gray",
      message: "Martin Gray liked your photo of the Eiffel Tower. 😍",
      time: "8 hours ago",
      bgClass: "",
      button: null,
    }
  ];