import { Inter } from "next/font/google";
import "./globals.css";
import "@/tailwind/style.css";
import "@/tailwind/tailwind.css"; 
 
import { FarcasterContextProvider } from "@/context/farcaster"; 
import { PrivyProviderComponent } from "@/components/provider/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SuperfunSocial",
  description: "Generated by SuperfunSocial",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PrivyProviderComponent >
          <FarcasterContextProvider>{children}</FarcasterContextProvider>
        </PrivyProviderComponent>
      </body>
    </html>
  );
}
